<a href="https://colab.research.google.com/github/klhftco/datagood-ADIHP/blob/main/Intro%20to%20Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to Python (written by Isabella Borkovic and Gloria Zhang; edited by Cameron Fozi and Esme Cohen; further revised by Jon Sulit and Stanley Kwon)

## Instructions
1. **MAKE A COPY OF THIS COLAB**
2. Read and pay close attention to documentation and source code.
3. Complete exercises.
4. Share with sulitjon@berkeley.edu and shkwon@berkeley.edu, and paste the link into this [Google Form](https://forms.gle/xaPzE39fmXby4owS6).



First let's take a look at some different data types in Python. When in doubt, use the type() function to determine what kind of data you are working with. This helps especially because some functions and operations can only have certain arguments so you would need to convert that data into a different type before applying the function.

In [ ]:
x = 7
type(x)

int

In [ ]:
y = 6.6
type(y)

float

In [ ]:
z = "hello"
type(z)

str

In [ ]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter
print(hello, len(hello))

hello 5


In [ ]:
hw = hello + ' ' + world  # String concatenation
print(hw)

hello world


In [ ]:
hw12 = '{} {} {}'.format(hello, world, 12)  # string formatting
print(hw12)

hello world 12


In [ ]:
s = "helLo"
print(s.capitalize())  # Capitalize the first letter of string and lowercase everything else
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.lower())       # Convert a string to lowercase; prints "hello"


Hello
HELLO
hello


Oftentimes, when we deal with data we have to convert strings to numbers. "7" is not the same as 7, so we have to typecast strings to ints. 

In [ ]:
x = "7" #x is a string
#If I try to add a number to x, an error will occur:
print(x + 3)



TypeError: ignored

In [ ]:
#however, if I typecast x to an integer, the environment will recognize x as an integer and add it to 3 properly
x_int = int(x)
print(x_int + 3)

10


In [ ]:
t = True
type(t)

bool

Next we will introduce booleans, which return either True or False given a piece of code. In the examples below, we look at numerical comparisons.

In [ ]:
# Here's x:

x

'7'

In [ ]:
x == 6

False

In [ ]:
x != 6

True

In [ ]:
x <= 10

TypeError: ignored

Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (`&&`, `||`, etc.):

In [ ]:
t, f = True, False
print(type(t))

<class 'bool'>


Now let's look at the operations: 

In [ ]:
print(t and f) # returns true only if both inputs are ture
print(t or f) # returns true if at least one input is true
print(not t) # returns true if the input is false; returns false if the input is true  
print(t != f)  # returns true if the two inputs are not equal
print(t == f) #returns true if the two inputs are equal

False
True
False
True
False


You can use if statements to make code that performs a certain action if the input is true.

In [ ]:
if (3 == 5 - 2):
  print("cowabunga")

cowabunga


If/else statements perform a certain action if the input is true, and a different action if the input is false.

In [ ]:
if (7 == 8):
  print("in the if statement")
else:
  print("in the else statement")

in the else statement


Next we will look at several conditional statements. Please note the indentation and syntax (colon). 

In [ ]:
if x == 6:
    print (" x is 6")
elif x == 5:
    print(" x is 5 ")
else:
    print("x is some number that is not 6 or 5")

x is some number that is not 6 or 5


Task 1a:
Create an if-elif-else statement that prints "tiny" if x is less than 8, prints "8" if x is equal to 8, and prints "ginormous" if x is greater than 8.

While loops perform an action as long as a certain expression is true (the expression after the while loop). In this example, the code prints the variable a as long as a is less than 10. After each loop, a increases by 1. Be careful of infinite loops when you use while loops!

In [ ]:
a = 1
while a < 10:
    print(a)
    a += 1 #another way of saying a = a + 1

1
2
3
4
5
6
7
8
9


Task 1b: Create a while loop that will print the multiples of five from 1 to 100.

Now we will take a look at the for loop which allows us to iterate through lists and other types of data. Range does not include the last element. Range(1, 4) would include the numbers 1,2, and 3, but not 4.

In [ ]:
range(1, 10)

range(1, 10)

In [ ]:
for x in range(1,10):
    print(x)

1
2
3
4
5
6
7
8
9


Now we will take a look at lists, which basically store data (that can have different types, so you can have a list with a string, a number, and a boolean) and how to slice them to output specific values. 

In [ ]:
numbers = [1, 2, 5, 6, 8, 9]

In [ ]:
numbers[:3]

[1, 2, 5]

In [ ]:
numbers[1:2]

[2]

In [ ]:
numbers[::2]

[1, 5, 8]

Task 2: Slice the list numbers so that you get every other number starting from 2. (You want [2,6,9])

Next we'll take a look at the different methods we can apply to lists, from adding new values to determining a value's index (i.e. position) in a list. Please note that indexes start at 0. 

In [ ]:
numbers.append(10)
numbers

[1, 2, 5, 6, 8, 9, 10]

In [ ]:
numbers.extend([3, 5])
numbers

[1, 2, 5, 6, 8, 9, 10, 3, 5]

In [ ]:
numbers.index(5)

2

In [ ]:
numbers.insert(0, 22)
numbers

[22, 1, 2, 5, 6, 8, 9, 10, 3, 5]

In [ ]:
numbers.pop(0)
numbers

[1, 2, 5, 6, 8, 9, 10, 3, 5]

In [ ]:
numbers.sort()
numbers

[1, 2, 3, 5, 5, 6, 8, 9, 10]

Now we will see examples of using list comprehensions to essentially "build" a new list from an existing list. Every list comprehension in Python includes 3 elements:

1. Output: what you want the output to be

2. Item: what is the object or value in the list (usually i)

3. Iterable: a list, set, sequence, tuple, or any other type of object that can return its elements one at a time.

We will also see that it does not matter what we name what we are iterating through, although it is recommended to make it related to your code. 

In [ ]:
[x/2 for x in numbers]

[0.5, 1.0, 1.5, 2.5, 2.5, 3.0, 4.0, 4.5, 5.0]

In [ ]:
[isabella_is_awesome for isabella_is_awesome in numbers if isabella_is_awesome % 2 == 0]

[2, 6, 8, 10]

The len() function is also useful to determine the number of items in lists, number of letters in a string, etc. 

In [ ]:
len(numbers)

9

In [ ]:
len("Ava")

3

In [ ]:
names = ["Cameron", "Esme", "Megan", "Omar", "Siddarth", "Jessica", "Thomas", "Thao", "Elena"]

Task 3: Create a list comprehension of names with more than 5 letters

Next we will look at dictionaries, which have keys and values. The keys in the next example are "blue", "red", "green", "yellow", and "purple" and can be used to access their corresponding values: 3, 5, 8, 9, 0. 

In [ ]:
d = {"blue": 3, "red": 5, "green": 8, "yellow": 9, "purple": 0}

In [ ]:
d["blue"]

3

In [ ]:
d.keys()

dict_keys(['blue', 'red', 'green', 'yellow', 'purple'])

In [ ]:
d.values()

dict_values([3, 5, 8, 9, 0])

In [ ]:
for name in names:
    print(name)

Cameron
Esme
Megan
Omar
Siddarth
Jessica
Thomas
Thao
Elena


In [ ]:
for bla in numbers:
    print(bla/2)

0.5
1.0
1.5
2.5
2.5
3.0
4.0
4.5
5.0


In [ ]:
for hey in d:
    print (hey)

blue
red
green
yellow
purple


Task 4: Create a for loop that goes through the names list and prints "Hello (name)" if the name is less than 6 letters. If the name is 6 to 9 letters, print the first five letters of the name using list slicing (list slicing works the same way for strings). If the name is 10 letters or more, print "Your name is interesting and beautiful. Heart eyes." 

##Creating Functions
We will often create functions to bundle a set of instructions that you want to use repeatedly. For a simple example, say you wanted to print "Hello" "How many bags would you like?" and "Have a nice day!" every time a customer came in. (this example does not make too much practical sense but ignore that for the sake of learning). If you had to type out all that every time, that would be very annoying. BUT, if you created a function that did all that for you, life would be easier, simpler, and more beautiful. Here's how!


1. Use the keyword def to declare the function and follow this up with the function name.
2. Add parameters to the function: they should be within the parentheses of the function. End your line with a colon.
3. Add statements that the functions should execute.
4. End your function with a return statement if the function should output something. Without the return statement, your function will return an object None.

Here's a function using the aforementioned example. It returns None because it has no return statement, and its only purpose is to print 3 statements

In [ ]:
def greeting ():
    print("Hello")
    print("How many bags would you like?")
    print("Have a nice day!")


Now I can call this function as many times as I want! When I call a function, I add parentheses after the function name and add parameters inside the function if applicable. My function greeting has no parameters, so I don't add any.

In [ ]:
greeting()

Hello
How many bags would you like?
Have a nice day!


This function is a little useless. Let's try making a slightly more useful greeting function that takes in a name and prints out "Hello name"

In [ ]:
def greeting (name):
    print("Hello " + name)


Now if I try calling greeting with the name "Isabella", I get this:

In [ ]:
greeting("Isabella")

Hello Isabella


Next week, we'll be looking at a function that converts strings such as "$123456" into numbers. If we input "$123456" into the function, it'll return the integer 123456. We'll use the built-in function `replace` to help us. Built in functions are built into python, so we don't need to define them. The replace function takes in 2 parameters—the first is the string to find and the second is the string to replace it with. Here is an example: 

In [ ]:
str = "replace all a's with the string '56b'"
str.replace('a', '56b')

"repl56bce 56bll 56b's with the string '56b'"

As you can see, to call the replace function, you write [string name].replace(param1, param2). With many built-in functions, such as append, that is the syntax in which you call functions. With others, such as len(), it is different. Look up examples of function documentation if you are confused on how to call a function!

We can also replace the a's with empty text ('') to just get rid of all a's. 

In [ ]:
str = "replace all a's with absolutely nothing"
str.replace('a', '')

"replce ll 's with bsolutely nothing"

Now let's write the function!

In [ ]:
# define a new function to remove the dollar signs 
def remove_dollar_sign(x): 
  # check if input is valid  
  if not x:
    return 0
  # since we know the first element is always a "$", we can simply slice the string and return the result casted into an integer 
  no_dollar_sign = int(x[1:].replace(",", ""))
  return no_dollar_sign

Testing the function!

In [ ]:
remove_dollar_sign("$45639")

45639

Yay it works amazing. 
#Task 6
Now let's build a function (that we will also use next week) to remove commas from a string such as "12,345" and convert the string into an integer. 

In [ ]:
#test your function
remove_commas_test = remove_commas("12,345") #should return 12345
print(remove_commas_test)

12345


## Intro to NumPy!! - partially taken from https://cs231n.github.io/python-numpy-tutorial/

NumPy is a Python library that provides a multidimensional array objects and an assortment of routines for fast operations on arrays.

Like with all libraries, we need to import the NumPy package to start using it.

In [ ]:
import numpy as np

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [ ]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)                  

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


Task 1: Create a 3 by 3 matrix of the numbers from 1-9 in any order. Assign it to the variable agatha.

Numpy also provides many functions to create arrays:

In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
b = np.ones((1,2))   # Create an array of all ones; number of arrays, number of elements
print(b)

[[1. 1.]]


In [ ]:
b2 = np.ones((2,4)) 
print(b2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


Numpy offers several ways to index into arrays.

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3] #which nested arrays, which elements within the arrays
print(b)

[[2 3]
 [6 7]]


Task 2: Use slicing to pull out the subarray consisting of the lower-right 2x2 matrix and assign it to the variable baltimore.

A slice of an array is a view into the same data, so modifying it will modify the original array.

In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

2
77


Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


Array Math: Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


* is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]
[29 67]


Task 3: Create the 2x2 identity matrix and assign it to the name charles. Multiply charles by 4 and add it to bartholomew. Then assign this new matrix to the variable dalton.

Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum:

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


Task 4: Print the sum of the elements of dalton.

*You* can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
print(x)
print("transpose\n", x.T)

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]


In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


You can also reshape arrays using the reshape method.

In [ ]:
reshape_array = np.array([[1,2],
                          [3,4],
                          [5,6]])

In [ ]:
np.reshape(reshape_array, (2, 3)) #number of rows, number of columns

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x.T

array([[1, 3],
       [2, 4]])

Task 5: Find the transpose of agatha and print it.


Done!